#!/bin/bash

echo "📝 Manual Webhook Test Instructions"
echo "===================================="
echo ""
echo "The webhook isn't registering automatically via API."
echo "This is because n8n needs to know its external URL."
echo ""
echo "OPTION 1: Quick Test (Recommended)"
echo "-----------------------------------"
echo "1. Open n8n in browser: http://192.168.1.237:5678"
echo "2. Find workflow: 'Tech LEAD - Telegram Bot Handler Simple'"
echo "3. Open the workflow"
echo "4. Click 'Execute Workflow' button"
echo "5. In another terminal, run:"
echo "   curl -X POST https://techlead.blucas.ca/webhook-test/telegram-bot-webhook \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"message\": {\"chat\": {\"id\": 191718134}, \"text\": \"/help\"}}'"
echo ""
echo "OPTION 2: Fix Permanently"
echo "-------------------------"
echo "Restart n8n container with proper webhook URL:"
echo ""
echo "docker stop n8n"
echo "docker run -d --rm --name n8n \\"
echo "  -p 5678:5678 \\"
echo "  -e WEBHOOK_URL=https://techlead.blucas.ca/ \\"
echo "  -e N8N_PROTOCOL=https \\"
echo "  -e N8N_HOST=techlead.blucas.ca \\"
echo "  -v ~/.n8n:/home/node/.n8n \\"
echo "  n8nio/n8n:latest"
echo ""
echo "This tells n8n that webhooks should use https://techlead.blucas.ca/"
echo "while keeping the editor at http://192.168.1.237:5678"