#!/bin/bash
# NocoDB Database Setup Script

echo "📊 Setting up NocoDB for Tech LEAD..."
echo ""
echo "Please complete these manual steps:"
echo ""
echo "1. Open NocoDB at: http://localhost:8810"
echo "2. Sign up/Login to NocoDB"
echo "3. Create a new Base/Project called 'techLEAD'"
echo "4. Once created, click on the Base to enter it"
echo "5. Look for 'Create Table' or import options"
echo ""
echo "After creating the base, you have two options:"
echo ""
echo "OPTION A: Create tables via UI"
echo "- Create table: projects_table"
echo "- Create table: decisions_log"
echo "- Create table: work_log"
echo ""
echo "OPTION B: Use SQL (if NocoDB supports direct SQL)"
echo "Run this SQL in the query interface:"
echo ""
cat /media/rob/Workspace/Development/techLEAD/schema/init.sql
echo ""
echo "Once tables are created:"
echo "1. Go to Account Settings → API Tokens"
echo "2. Create a new API token"
echo "3. Copy the token"
echo "4. Update /media/rob/Workspace/Development/techLEAD/.env with:"
echo "   NOCODB_API_TOKEN=your-actual-token-here"
echo ""
echo "Then insert your first project:"
echo "INSERT INTO projects_table (repository_url, project_identifier, status, telegram_chat_id, context_summary)"
echo "VALUES ('https://github.com/YOUR_USER/YOUR_REPO', 'PROJECT_NAME', 'active', 'YOUR_CHAT_ID', 'Project description');"